POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Echezona Oji",
  "number": "040-2345678"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "",
  "number": "040-2345678"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Echezona Oji",
  "number": ""
}